# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .provider import *
from .self_signed_certificate import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "tls-self-signed-cert",
  "mod": "index",
  "fqn": "pulumi_tls_self_signed_cert",
  "classes": {
   "tls-self-signed-cert:index:SelfSignedCertificate": "SelfSignedCertificate"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "tls-self-signed-cert",
  "token": "pulumi:providers:tls-self-signed-cert",
  "fqn": "pulumi_tls_self_signed_cert",
  "class": "Provider"
 }
]
"""
)
